### ISSUE TITLE
Search result page doesn't work in production

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal.com#183] opened 2017-08-10 01:36 UTC
To reproduce, go to https://sonarwhal.com/search?q=doc&page=5

A 404 page is shown instead of a search result page. This can't be reproduced in local for some reason.

**Comment by alrra** [comment] 2017-08-10 01:40
Ref: https://github.com/sonarwhal/sonarwhal.com/pull/164#issuecomment-321426608.

**Comment by alrra** [comment] 2017-08-10 01:50
Closing this as the problem is with #164.

**Comment by alrra** [comment] 2017-08-10 19:42
Even with the code from #164 being fixed, and everything working locally, the search doesn't work on the live site.

**Comment by qzhou1607** [comment] 2017-08-10 21:21
@alrra Just found that https://sonarwhal.com/scanner returns 404 page as well. I wonder if we have settings somewhere blocking the `get` requests for `scanner`, and `search` was blocked originally as well. @molant is that right?

**Comment by molant** [comment] 2017-08-10 21:23
This is something related to IIS's `web.config`. I'll take a look.

**Comment by alrra** [comment] 2017-08-10 22:07
It's fixed now.

**Comment by molant** [comment] 2017-08-10 22:07
OK, so it wasn't related to `web.config`.
The problem is that the node process requires the `_config.yml` file in the root and right now we are not copying that file into the server. I've manually update it but @alrra or @qzhou1607 should update the scripts to make sure it is in the root

**Comment by alrra** [comment] 2017-08-10 22:08
> I've manually update it but @alrra or @qzhou1607 should update the scripts to make sure it is in the root

Ok.

**Comment by alrra** [comment] 2017-08-10 22:15
- [ ] Update web.config.

**Comment by qzhou1607** [comment] 2017-08-10 22:42
Meaning `_config.yml` should be added to [this](https://github.com/sonarwhal/sonarwhal.com/blob/master/.travis/update-site.sh#L10) list?
>update the scripts to make sure it is in the root

Ohhh was that because of the api credentials? Then I wonder if the google analytics we have in the site has worked since we had it ... We had the google analytics id there as well.

>the node process requires the `_config.yml` file

**Comment by alrra** [comment] 2017-08-11 05:05
> Meaning `_config.yml` should be added to [this](https://github.com/sonarwhal/sonarwhal.com/blob/master/.travis/update-site.sh#L10) list?

Yes.

**Closed** 2017-08-11 05:04 UTC

**Comment by molant** [comment] 2017-08-11 05:57
> Then I wonder if the google analytics we have in the site has worked since we had it ... 

Yes, that file is only required for the service and search in the server. The rest is static.
